# Jekyll settings
#
title: Stage de distillation
email: webmestre@arboriculteurs-lichtenberg.eu
lang: fr-FR
description: 
  Un reportage sur la formation à la distillation artisanale donnée le 9/3/2019 à Lichtenberg : préparation des fruits, première et deuxième passe de distillation, finition des eaux de vie, dégustation, règlementation.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.arboriculteurs-lichtenberg.eu" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  jekyll
nav_direction: vertical # vertical, horizontal 
image_dir: "assets/images"
sound_dir: "assets/sounds"
sound_source: ""
collections:
    - sections
# Build settings
markdown: kramdown
plugins:
  - github-pages
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
  - _site
include:
  - assets
